---
version: '2.1'
services:
    homeassistant:
        image: homeassistant/home-assistant:latest
        devices:
            - /dev/gpiomem:/dev/gpiomem
        container_name: homeassistant
        network_mode: host
        environment:
            - TZ=Europe/Berlin
        volumes:
            - /home/raspberry/docker/homeAssistant/data:/config
        restart: unless-stopped
